# Generated by Django 5.0.5 on 2024-05-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('change_is_active_status', 'Can change user`s status')]},
        ),
    ]
