# Generated by Django 5.0.5 on 2024-05-10 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailingmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='название рассылки')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='дата и время первой отправки рассылки')),
                ('period', models.CharField(max_length=50, verbose_name='периодичность рассылки')),
                ('status', models.CharField(max_length=50, verbose_name='статус рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingmessage', verbose_name='сообщение рассылки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='менеджер рассылки')),
                ('target', models.ManyToManyField(to='mailing.client', verbose_name='получатели рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
