# Generated by Django 5.0.5 on 2024-05-11 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_client_email_alter_mailing_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_last_attempt', models.DateTimeField(auto_now=True, verbose_name='дата и время последней попытки')),
                ('status', models.CharField(choices=[('success', 'успешно'), ('fail', 'неуспешно')], default='', max_length=50, verbose_name='статус попытки')),
                ('server_response', models.CharField(blank=True, max_length=500, null=True, verbose_name='ответ почтового сервера')),
                ('mailing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'попытки',
            },
        ),
    ]
