# Generated by Django 5.0.5 on 2024-05-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_mailinglogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingLogs',
            new_name='MailingLog',
        ),
    ]
