# Generated by Django 5.0.5 on 2024-05-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_rename_mailinglogs_mailinglog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglog',
            options={'verbose_name': 'попытка (логи рассылки)', 'verbose_name_plural': 'попытки (логи рассылки)'},
        ),
    ]
