# Generated by Django 5.0.5 on 2024-05-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailinglog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='period',
            field=models.CharField(choices=[('once', 'один раз'), ('daily', 'ежедневно'), ('weekly', 'еженедельно'), ('monthly', 'ежемесячно')], max_length=50, verbose_name='периодичность рассылки'),
        ),
    ]
